// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwmkkqztjqidaqgcughu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3bWtrcXp0anFpZGFxZ2N1Z2h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMjQwMzUsImV4cCI6MjA2MzcwMDAzNX0.UqPnYzTT_y0TadV7Z66A6vYCqK8IKyz4dkA7tPLbdcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);